name: weather_project
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  jiffy: ^5.0.0
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  bloc: ^9.0.0
  flutter_bounce: ^1.1.0
  bounce: ^1.0.2
  equatable: ^2.0.7
  cloud_firestore: ^5.6.5
  geolocator: ^13.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.2
  provider: ^6.1.2
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

  mockito: ^5.4.5
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.15
  test: ^1.16.0

flutter:
  assets:
    - assets/logo/logo.png

  uses-material-design: true

flutter_launcher_icons:
  android: 'logo_icon'
  ios: true
  image_path: 'assets/logo/logo.png'
  min_sdk_android: 21
  web:
    generate: false
    image_path: 'path/to/image.png'
  windows:
    generate: false
    image_path: 'path/to/image.png'
  macos:
    generate: false
    image_path: 'path/to/image.png'
